const services=[
{code:'UT',name:'Ultrasonic Testing',short:'Sound-wave inspection for evaluating internal condition and material thickness, where suitable.',image:'ut-licensed.jpg',what:'Ultrasonic Testing uses high-frequency sound waves introduced into a component through a probe and couplant.',principle:'The instrument analyses returning echoes to help locate reflectors or measure material thickness. Technique and interpretation depend on geometry, material and procedure.',detect:'Internal reflectors · selected weld discontinuities · thickness variation',applications:'Welds · plates · pipes · components (subject to access and scope)',limits:'Surface condition, geometry, material structure and access can affect results. Confirm suitability for the part.',equipment:'Ultrasonic flaw detector and transducer (confirm configuration)'},
{code:'RT',name:'Radiographic Testing',short:'Radiation-based imaging used to examine internal features in suitable components.',image:'rt-user.jpg',what:'Radiographic Testing forms an image by passing X-rays or gamma radiation through a component onto a detector or film.',principle:'Differences in transmitted radiation can reveal changes in thickness or density. Controlled access and radiation safety arrangements are essential.',detect:'Volumetric changes and internal features that create image contrast',applications:'Welds · castings · selected fabricated components (subject to scope)',limits:'Access, thickness, orientation and safety controls affect method selection and results.',equipment:'Radiation source and imaging system (confirm availability)'},
{code:'MT',name:'Magnetic Particle Testing',short:'Surface and near-surface examination for suitable ferromagnetic materials.',image:'ndt-mt.webp',what:'Magnetic Particle Testing magnetises a ferromagnetic component and applies visible or fluorescent particles.',principle:'A surface-breaking discontinuity can disturb the magnetic field, attracting particles to form an indication.',detect:'Surface and near-surface discontinuities in ferromagnetic materials',applications:'Welds · forgings · ferromagnetic components (subject to access)',limits:'Only suitable for ferromagnetic materials; surface condition, magnetisation direction and demagnetisation needs matter.',equipment:'Magnetising equipment and inspection particles (confirm setup)'},
{code:'PT',name:'Liquid Penetrant Testing',short:'A surface examination method for finding discontinuities open to the surface.',image:'ndt-pt.webp',what:'Liquid Penetrant Testing applies a low-viscosity penetrant to a clean, non-porous surface.',principle:'Penetrant enters surface openings by capillary action. After excess is removed, developer draws it back out to create visible indications.',detect:'Surface-breaking discontinuities on non-porous materials',applications:'Welds · machined parts · non-ferrous components (subject to scope)',limits:'Finds only discontinuities open to the surface; thorough cleaning and suitable surface condition are needed.',equipment:'Cleaner, penetrant, remover and developer (confirm consumables)'},
{code:'VT',name:'Visual Testing',short:'Direct or assisted visual examination of accessible surfaces and features.',image:'ndt-vt.webp',what:'Visual Testing examines an accessible surface using direct viewing or suitable optical aids.',principle:'An inspector checks visible features against the agreed scope and acceptance criteria, recording relevant observations.',detect:'Visible surface conditions, dimensions or workmanship features within the defined scope',applications:'Welds · structures · components with accessible surfaces',limits:'Results depend on access, lighting, cleanliness, viewing angle and agreed criteria.',equipment:'Lighting and optical aids as required (confirm scope)'},
{code:'UTM',name:'Ultrasonic Thickness Measurement',short:'Ultrasonic measurement to assess remaining wall thickness at agreed locations.',image:'ndt-utm.webp',what:'Ultrasonic thickness measurement estimates the distance between a surface and the back wall using sound-wave travel time.',principle:'A probe sends an acoustic pulse and the instrument converts the returning echo time to a thickness reading using the configured velocity.',detect:'Local thickness values at accessible measurement points',applications:'Pipes · tanks · plates · components (subject to access and surface)',limits:'Coating, curvature, pitting, surface condition and calibration affect readings and coverage.',equipment:'Thickness gauge and compatible probe (confirm configuration)'}
];
const photo=(asset,w=900)=>asset.startsWith('photo-')?`https://images.unsplash.com/${asset}?auto=format&fit=crop&w=${w}&q=82`:new URL(asset,document.baseURI).href;
const grid=document.querySelector('#serviceGrid'),select=document.querySelector('#serviceSelect');
services.forEach((s,i)=>{grid.insertAdjacentHTML('beforeend',`<article class="service-card"><div class="service-img"><img src="${photo(s.image,750)}" alt="${s.name} inspection method" loading="lazy"><span>${s.code} / METHOD</span><button class="round" data-details="${i}" aria-label="View ${s.name} details">↗</button></div><div class="service-info"><div><span class="service-code">NDT METHOD / ${s.code}</span><h3>${s.name}</h3><p>${s.short}</p></div><div class="service-actions"><button class="detail-btn" data-details="${i}">View Details <span>↗</span></button><button class="request-btn" data-request="${s.name}">Request this service</button></div></div></article>`);select.insertAdjacentHTML('beforeend',`<option value="${s.name}">${s.name} (${s.code}) — availability to confirm</option>`)});
const modal=document.querySelector('#serviceModal'),form=document.querySelector('#enquiryForm'),status=document.querySelector('#formStatus');let lastFocus;
function openModal(i){const s=services[i];lastFocus=document.activeElement;document.querySelector('#modalEyebrow').textContent=`NDT METHOD / ${s.code}`;document.querySelector('#modalTitle').textContent=s.name;document.querySelector('#modalIntro').textContent=s.what;document.querySelector('.modal-image img').src=photo(s.image,1000);document.querySelector('#modalDetails').innerHTML=[['Working principle',s.principle],['What it can detect',s.detect],['Typical applications',s.applications],['Limitations',s.limits],['Typical equipment',s.equipment]].map(x=>`<div><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');document.querySelector('.modal-close').focus()}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');lastFocus?.focus()}
grid.addEventListener('click',e=>{const d=e.target.closest('[data-details]'),r=e.target.closest('[data-request]');if(d)openModal(+d.dataset.details);if(r){select.value=r.dataset.request;location.hash='enquiry'}});document.querySelector('.modal-close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target.hasAttribute('data-close'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))closeModal();if(e.key==='Tab'&&modal.classList.contains('open')){const els=[...modal.querySelectorAll('button,a')].filter(x=>x.offsetParent!==null),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});document.querySelector('.modal-request').addEventListener('click',()=>{select.value=document.querySelector('#modalTitle').textContent;closeModal()});
const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{let on=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',on);nav.classList.toggle('nav-open',on)});nav.addEventListener('click',e=>{if(e.target.closest('a')){menu.setAttribute('aria-expanded','false');nav.classList.remove('nav-open')}});
const header=document.querySelector('.topbar');window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>30),{passive:true});
form.addEventListener('submit',async e=>{
 e.preventDefault();
 if(!form.reportValidity())return;
 const fields=Object.fromEntries(new FormData(form));
 const payload={...fields,_subject:'UGNAA inspection enquiry — '+fields.service,_replyto:fields.email};
 status.textContent='Sending your enquiry…';
 const button=form.querySelector('button[type="submit"]');button.disabled=true;
 try{
  const response=await fetch('https://formsubmit.co/ajax/ugnaa.ndt@gmail.com',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});
  const result=await response.json();
  if(!response.ok||result.success===false)throw new Error(result.message||'Submission failed');
  form.reset();status.textContent='Thank you. Your inspection request has been sent to UGNAA. Our team will contact you shortly.';
 }catch(error){status.textContent='We could not send your request right now. Please email ugnaa.ndt@gmail.com or call +91 9241143166.';}
 finally{button.disabled=false;}
});
